### ISSUE TITLE
Suggestion setPositiveButton compatibility

### ISSUE THREAD

**Issue by KennyGoers** [yarolegovich/LovelyDialog#13]
On thing I've noticed is that the setPositiveButton and related calls use View OnClick instead of the Dialog OnClick, this makes converting existing dialogs more work than they need to be.

**Comment by yarolegovich** [comment]
You can now use 
````java
LovelyDialogCompat.wrap(yourOldImplementationOfDialogClickListener);
````
I decided not to pollute code with method overloads.
