### ISSUE TITLE
Password EditText in LovelyTextInputDialog

### ISSUE THREAD

**Issue by Alexandersch** [yarolegovich/LovelyDialog#14]
Hi,

I tried to do this:
.setInputType(InputType.TYPE_TEXT_VARIATION_PASSWORD)

But that doesn't work... 

Does anyone have an idea of how to use a password mask in this textinput?

**Comment by yarolegovich** [comment]
Hi, have you tried .setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD)?

**Comment by Alexandersch** [comment]
Hi, not yet, but i'll try that later!

**Comment by Alexandersch** [comment]
It works, many thanks!
