### ISSUE TITLE
Choice selected in Dialogue

### ISSUE THREAD

**Issue by karopass** [yarolegovich/LovelyDialog#19]
Hi ! I want use this dialogue for my notification preference. I want keep Notification on checkbox default checked. if user uncheck it...I want keep it unchecked. Can I do it in this ?
Thanks

**Comment by yarolegovich** [comment]
Hi. Yes, you can. 
```java
new LovelyChoiceDialog()
    .setItemsMultiChoice(items, checkedStates, listener)
    .show();
```
