### ISSUE TITLE
Lovely Library! More color options?

### ISSUE THREAD

**Issue by MaximilianKeppeler** [yarolegovich/LovelyDialog#21]
Great library, I will use it for my app. Could you maybe add more color options? 

Since my app offers a dark mode, I need to be able to change the color of the background of the dialog and the text colors. Otherwise it's perfect! Thank you very much.

**Comment by yarolegovich** [comment]
I assume that passing a custom theme as a second argument to dialog's constructor is what you are looking for.

**Comment by MaximilianKeppeler** [comment]
Hi, thanks for your reply. I have seen it, but how can I change the background and text colors with a theme? Are there special attributes?

**Comment by yarolegovich** [comment]
Tell me please what are you trying to achieve and what have you already tried.

**Comment by yarolegovich** [comment]
Back to the issue, there is a background attribute:
```xml
<item name="android:background">@color/dialogBackground</item>
```
Lets suppose that's what you were looking for.
