### ISSUE TITLE
ViewPager not working when .setView is used

### ISSUE THREAD

**Issue by nfcurti** [yarolegovich/LovelyDialog#22]
I tried to merge the Dialog I was using to a LovelyCustomDialog, but the viewpagers doesnt seem to get the items, as it worked fine on a simple dialog, I dont know whether this is a Lovely Dialogs error or mine. Any clue?

```
LayoutInflater inflater = this.getLayoutInflater();
final View dialogView = inflater.inflate(R.layout.reviewleer, null);
adaptervp = new MyPagerAdapter(this, arrayReview);
ViewPager viewPager = (ViewPager) dialogView.findViewById(R.id.viewpager);
viewPager.setAdapter(adaptervp);

**new LovelyCustomDialog(this)
                .setView(dialogView )
                .setTopColorRes(R.color.vimeo)
                .setTitle("asd")
                .setMessage("asd")
                .setIcon(R.drawable.ic_settings_ethernet_white_24dp)
                .show();**



```

**Comment by yarolegovich** [comment]
I suppose you used DialogFragments. LovelyDialog doesn't work with fragments

**Comment by nfcurti** [comment]
Im not using DialogFragments, just trying to inflate the custom view into the LovelyDialog

**Comment by yarolegovich** [comment]
If your ViewPager adapter works with fragments, you won't be able to use it in the dialog.
