### ISSUE TITLE
Default selected item in single choice

### ISSUE THREAD

**Issue by zainullahdev** [yarolegovich/LovelyDialog#26]
Hi,

I have a simple dialog with 2 options, I am saving the selected value so users can change whenever they want.

I want to show the previous selected value

how can i do this ?

**Comment by sidhuparas** [comment]
Yes, I want the same. There should be some pre-selected value. If you add this feature, it would be great.

**Comment by yarolegovich** [comment]
There is a sample app in this repository which contains an example of how to use a custom `ArrayAdapter` with a single choice dialog.
