### ISSUE TITLE
Buttons gravity

### ISSUE THREAD

**Issue by henengel** [yarolegovich/LovelyDialog#28]
Hi there,
Is there any way to set the gravity of the buttons?
I saw that it is possible with the message and title, but not the buttons

Thank you

**Comment by AhmedSamir213** [comment]
hi 
please . i need to set the confirmation button gravity to the center how can i do this ? 
Thanks ...

**Comment by yarolegovich** [comment]
You can use [this API](https://github.com/yarolegovich/LovelyDialog#access-to-inner-view-objects) to find button objects in the root view and modify their layout parameters.
