### ISSUE TITLE
How to dismiss the LovelyCustomDialog?

### ISSUE THREAD

**Issue by amitkhairnar44** [yarolegovich/LovelyDialog#29]
I'm using custom view for displaying two EditTexts.
But i'm unable to dismiss the dialog.
And i'm checking whether they are empty or not. If empty, then an error is displayed on edittext.
And if not empty then performing some task.
But the problem here is after performing the tasks the dialog is not dismissed.

**Comment by BizarreBoy** [comment]
@amitkhairnar44 
Since you have created custom layout with custom buttons you'll have to manually dismiss the dialog.
Like this:

`final LovelyCustomDialog dialog = new LovelyCustomDialog(context);`
`dialog.setListener(R.id.btn_confirm, new View.OnClickListener() {`
`           @Override`
           ` public void onClick(View v) {`
            `    //what you want to do`
           `     dialog.dismiss();`
        `    }`
      `  });`

**Comment by amitkhairnar44** [comment]
Thanks for the reply :) @BizarreBoy
