### ISSUE TITLE
Can't set TopColor to my choice

### ISSUE THREAD

**Issue by alexakasanjeev** [yarolegovich/LovelyDialog#3]
In the tutorial you have set the topColor like this
`.setTopColor(color(R.color.indigo))`
you are sending the color id into some kind of color90 function what is it. And if I try this
`setTopColor(R.color.my_custom_color)` 
it is always showing same dark grey type of color ,

**Comment by yarolegovich** [comment]
Hi, this is to show that you need to load this color from resources by its
id. Color function is just ContextCompat.getColor(context,
R.color.someColor)

**Comment by alexakasanjeev** [comment]
Thank you ,it worked
