### ISSUE TITLE
How to remove top space in LovelyCustomDialog

### ISSUE THREAD

**Issue by Awais-Ali** [yarolegovich/LovelyDialog#33]
![imgpsh_fullsize](https://user-images.githubusercontent.com/7523476/30963289-5924355e-a466-11e7-8bc4-9426c63a2ddb.png)

**Comment by thedude61636** [comment]
use my fork for the project, or maybe just set the background color of the dialog to match your color, just make sure you use the commit version instead of the -SNAPSHOT

**Comment by yarolegovich** [comment]
It's impossible. If anyone has a similar issue, you're using the library wrong.
