### ISSUE TITLE
Get the editText of TextInputDialog 

### ISSUE THREAD

**Issue by yehiahd** [yarolegovich/LovelyDialog#35]
I think the TextInputDialog should have a method that returns the EditText of the dialog itself so we can edit it programmatically Like settings the text change inputType ...etc

**Comment by yarolegovich** [comment]
Most probably you don't need this anymore, but in the current version of the library you can achieve this [as shown here](https://github.com/yarolegovich/LovelyDialog/blob/master/sample/src/main/java/com/yarolegovich/sample/MainActivity.java#L195).
