### ISSUE TITLE
Diable auto dismiss feature

### ISSUE THREAD

**Issue by Suyogms1** [yarolegovich/LovelyDialog#37]
Need to disable auto dismiss /cancel feature for all dialogs :)

**Comment by yarolegovich** [comment]
When you call `show()` or `create()` method  an actual `Dialog` object is returned, so you can just call its appropriate method:
```java
Dialog dialog = new Lovely*Dialog(context)
    ...
   .create();
dialog.setCancelable(false);
dialog.show();
```
