### ISSUE TITLE
How to change font size ?

### ISSUE THREAD

**Issue by fawxyz** [yarolegovich/LovelyDialog#38]
i tried adding textSize in style.xml but it only affect the button (positive, negative & neutral button). The title and description text stay same.
```

<style name="quitAlert" parent="Theme.AppCompat.Light.Dialog.Alert">
        <item name="android:gravity">center</item>
        <item name="android:textSize">50sp</item>
 </style>
```

**Comment by yarolegovich** [comment]
Try using [this API](https://github.com/yarolegovich/LovelyDialog#access-to-inner-view-objects).
