### ISSUE TITLE
Put buttons vertically

### ISSUE THREAD

**Issue by JockerGG** [yarolegovich/LovelyDialog#39]
Hello! your library is awesome, but i have a little question.

Can i put the buttons of standar dialog vertically?

Like this:

![image](https://user-images.githubusercontent.com/6700974/35757795-55f58e62-0836-11e8-99bf-c266ca3ab0d7.png)

Thanks for your time!

Have good day!

**Comment by yarolegovich** [comment]
Hi. First, update your dependency to use the latest version, currently -`1.1.0`. Then use:
```java
new LovelyStandardDialog(context, LovelyStandardDialog.ButtonLayout.VERTICAL)
...
```

**Comment by JockerGG** [comment]
oh! thanks very so much!
