### ISSUE TITLE
Using Fragments vs .setTopColor and .setButtonsColor

### ISSUE THREAD

**Issue by christianv07** [yarolegovich/LovelyDialog#4]
Hello, I have run into 2 issues.

I'm using Fragments to inflate my main_layout because of the way I use a Navigation Drawer on my app.

So while using:

new LovelyStandardDialog(this)
      .setTopColor(color(R.color.indigo))
      .setButtonsColor(color(R.color.darkDeepOrange))
      .setIcon(R.drawable.ic_star_border_white_36dp)
      .setTitle(R.string.rate_title) 
      .setMessage(R.string.rate_message)
      .setPositiveButton(android.R.string.ok, new View.OnClickListener() {
          @Override
          public void onClick(View v) {
              Toast.makeText(context, "positive clicked", Toast.LENGTH_SHORT).show();
          }
      }) 
      .setNegativeButton(android.R.string.no, null)
      .show();

I ran into an issue where I had to replace the "new LovelyStandardDialog(this)" for "new LovelyStandardDialog(getActivity())" so I could get rid of the errors, but while trying to use both .setTopColor(...) and .setButtonsColor(...) I always get an error message saying "method called expected". 

I'm fairly new to using libraries so I'm probably doing something wrong, any suggestions?

Here's my code:

![lovelydialogfragmentissue](https://cloud.githubusercontent.com/assets/8799179/14875187/087e807e-0cd6-11e6-98fc-6d62fda26d17.png)

**Comment by yarolegovich** [comment]
Hi!
Before using any method - you need to create it. I assume you don't have color() method to load color res
add 
```
private int color(int colorRes) {
     return ContextCompat.getColor(getActivity(), colorRes);
}
```
to your class.

**Comment by christianv07** [comment]
Hey, thanks a lot @yarolegovich ! Learned something new :D
