### ISSUE TITLE
LovelyTextInputDialog - no negative button

### ISSUE THREAD

**Issue by hatak30** [yarolegovich/LovelyDialog#5]
Hi 

Is it possible that you will add negative button to LovelyTextInputDialog?

**Comment by cliffgr** [comment]
.setNegativeButton()

**Comment by hatak30** [comment]
Sorry but I can't find .setNegativeButton on LovelyTextInputDialog, it has only confirmation button support.

**Comment by yarolegovich** [comment]
Hi, you are right - currently there is no negative button for TextInputDialog. Maybe I will introduce it, but a bit later - currently I'm busy on other projects.
You can also try to add it yourself and make a pull request :)
