### ISSUE TITLE
Adding Fragment to a view

### ISSUE THREAD

**Issue by MaxToyberman** [yarolegovich/LovelyDialog#7]
Is it possible to add a fragment to the view ?

I have tried this :

```
              Dialog showw = new LovelyCustomDialog(this)
                        .setTopColorRes(R.color.yellow)
                        .setIcon(R.drawable.ic_menu_camera)
                        .setView(R.layout.fragment_maps)
                        .configureView(new LovelyCustomDialog.ViewConfigurator() {
                            public ImageView mImageView;

                            @Override
                            public void configureView(final View v) {


   FrameLayout mapContainer= (FrameLayout) v.findViewById(R.id.mapView);

                                    SupportMapFragment fragment = new SupportMapFragment();
                                    FragmentTransaction transaction = getSupportFragmentManager().beginTransaction();
                                    transaction.add(mapContainer.getId(), fragment).commit();

                            }
                        })
                        .show();

```

**Comment by yarolegovich** [comment]
Unfortunately this is not possible now. Maybe I should implement LovelyFragmentDialog and make it use DialogFragment, but currently everything is built on standard alert dialogs (and I think it is not possible to embed a fragment there). I will update this thread if publish an update.

**Comment by MaxToyberman** [comment]
I have managed to do this with DialogFragment... but this is not the same.
Thank you

**Comment by pzienowicz** [comment]
+1
I am waiting for this feature. Can you specify, when you are going to do this?

**Comment by yarolegovich** [comment]
If the need for this is only because of SupportMapFragment, you can try using LovelyCustomDialog and add MapView directly to it.

**Comment by pzienowicz** [comment]
@yarolegovich, I wanted to add tabs into my dialog, so now I need to create DialogFragment.
Please consider creating new dialog, based on DialogFragment.

**Comment by yarolegovich** [comment]
@pzienowicz this will be very problematic because of implicit reference to enclosing class in the inner classes. Imagine we are showing a dialog from inside the activity:
```java
new LovelyFragmentDialog(context)
   .setView(R.layout.some_layout)
   .configureView((v, fragmentManager) -> {
      //How to preserve this configuration across orientation changes, taking into account 
      //it has a reference to enclosing activity?
   })
   .show();
```
Maybe I will add some builder-class to easily initialize top color, top icon and title but you will still need to create your own class that extends DialogFragment.

**Comment by yarolegovich** [comment]
Just consider using a `DialogFragment` subclass.
